apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::761016821565:role/eksctl-eksctl-mydemo-nodegroup-ng--NodeInstanceRole-n9CNyBtxiYlk
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::761016821565:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-09T12:11:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1472"
  uid: 9c113b40-267c-41af-b91e-81ea9b3fdf20
